### ISSUE TITLE
Password LDAP n'est pas update 

### ISSUE THREAD

**Issue by OSiG43** [REZAL-AM-KIN/niki-s#40]
Si le mot de passe niki change, le mot de passe reste inchangé dans ldap.
Les autres champs s'update correctement.

**Comment by lenwe171175** [comment]
Comment as tu changé le mdp ?

**Comment by OSiG43** [comment]
Via la form de changement de mot de passe.
J'ai ensuite en théorie forcé l'actualisation ldpa en enregistrant le
profile depuis l'interface admin mais ça n'a pas non plus update le mot de
passe

Le jeu. 19 janv. 2023 à 06:28, Robin SYLVESTRE ***@***.***> a
écrit :

**Comment by lenwe171175** [comment]
Premier élément de diagnostic...
Lorsque le mot de passe est changé par PasswordChangeView ou PasswordResetConfirmView, la fonction set_password est bien appelée : le champ "password" est changé mais pas le champ "ldap_password" (vérification effectuée via shell)
=> Besoin de modifier la fonction set_password du modèle Utilisateur
